title: UTSRWR
description: Blog campuran kuliner, film, dan teknologi
url: "https://utsrwr.github.io"
baseurl: ""

permalink: /:year/:month/:title.html

markdown: kramdown
theme: null

author:
  name: UTSRWR

plugins:
  - jekyll-feed
  - jekyll-sitemap

compress_html:
  clippings: all

defaults:
  - scope:
      path: ""
      type: posts
    values:
      thumbnail: /assets/img/default.jpg

paginate: 6
paginate_path: "/page/:num/"
plugins:
  - jekyll-paginate
