title: UTSRWR
description: Blog campuran kuliner, film, dan teknologi
url: "https://utsrwr.github.io"
baseurl: ""

author:
  name: UTSRWR

permalink: /:year/:month/:title.html

markdown: kramdown
theme: null

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 6
paginate_path: "/page/:num/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      thumbnail: /assets/img/default.jpg

sass:
  style: compressed
